-- Create DB
DROP DATABASE IF EXISTS reimbursement;

CREATE DATABASE reimbursement CHARACTER SET utf8 COLLATE=utf8_bin;
USE reimbursement;

-- Create Tables

CREATE TABLE types(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`limit` DECIMAL(12,2) UNSIGNED NOT NULL,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE users(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	roleID INT UNSIGNED NOT NULL,
	login VARCHAR(60) NOT NULL,
	password VARCHAR(256) NOT NULL
);

CREATE TABLE roles(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT NULL
);

CREATE TABLE rates(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	amount DECIMAL(12,2) UNSIGNED NOT NULL,
	`limit` DECIMAL(12,2) UNSIGNED NOT NULL,
	description VARCHAR(30) NOT NULL
);

CREATE TABLE mileages(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	claimID INT UNSIGNED NOT NULL,
	distance INT UNSIGNED NOT NULL
);

CREATE TABLE limits(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	amount DECIMAL(12,2) UNSIGNED NOT NULL,
	description VARCHAR(30) NOT NULL
);

CREATE TABLE claims(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	userID INT UNSIGNED NOT NULL,
	dateFrom DATE NOT NULL,
	dateTo DATE NOT NULL,
	ignoredDays JSON NOT NULL
);

CREATE TABLE receipts(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	claimID INT UNSIGNED NOT NULL,
	typeID INT UNSIGNED NOT NULL,
	amount DECIMAL(12,2) NOT NULL
);

-- Add foreign keys 

ALTER TABLE users ADD CONSTRAINT role_fk FOREIGN KEY (roleID) 
REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE claims ADD CONSTRAINT user_fk FOREIGN KEY (userID) 
REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE receipts ADD CONSTRAINT receipts_claim_fk FOREIGN KEY (claimID) 
REFERENCES claims(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE receipts ADD CONSTRAINT type_fk FOREIGN KEY (typeID) 
REFERENCES types(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE mileages ADD CONSTRAINT mileages_claim_fk FOREIGN KEY (claimID) 
REFERENCES claims(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Fill tables

INSERT INTO types VALUES
(NULL,150,'taxi'),
(NULL,300,'hotel'),
(NULL,300,'plane ticket'),
(NULL,200,'train');

INSERT INTO rates VALUES
(NULL,15,350,'allowance'),
(NULL,0.3,300,'mileage');

INSERT INTO limits VALUES
(NULL,500,'total'),
(NULL,300,'distance');

INSERT INTO roles VALUES
(NULL,'user'),
(NULL,'admin');

INSERT INTO users VALUES
(NULL,1,"user","user"),
(NULL,2,"admin","admin");